version: '3'
services:
    visionaitest:
        build:
            context: .
        container_name: visionaitest
        ports:
            - 3000:3000
        volumes:
            - .:/workspace
            # this speeds up things so much, we avoid mounting our own node_modules, so as to use the container's file system!
            - /workspace/node_modules 
        command: /bin/bash -c "cd /workspace/nextjs-dashboard    && npm install && npm run build && npm run start"