FROM node:21-bookworm

# RUN apt-get update && apt-get install -y nodejs npm node-libnpx

# EXPOSE 3000

ENV PORT 3000

WORKDIR /usr/src/app

COPY nextjs-dashboard/package*.json ./

RUN npm install

COPY nextjs-dashboard/* ./

RUN npm run build && npm run start